### PR TITLE
Changing default slot to be 1

### PR DESCRIPTION
**Pull request by noliran**
Hi Yussuf,

Thanks for making this awesome contribution. Integrating with it was a breeze.. :)
This PR will change the default slot to be 1 rather than 2.

Best regards,
Noam

### CODE REVIEW

**Comment by pp3345** [comment]
Hi @noliran,

thank you for your pull request. I've deliberately chosen to select slot 2 as default because that's the slot KeeChallenge uses per default. I am open to changing that though. Would you mind sharing why you think that slot 1 would be a better default? Perhaps I think it would also be a good idea to just remember the last slot that was used since most users will probably only use either of the two slots and it's rather annoying to select the right one every time if it isn't default.

**Comment by noliran** [comment]
Hi Yussuf,

I see, makes sense. You're right - a better solution would be to just remember the slot that was last used. Alternatively, we could take it as a parameter as part of the intent.

Do you have a preference?

**Comment by aol-nnov** [comment]
+1 for parameter!
also, it could be optional and if missing, current behaviour will be in effect.

**Comment by pp3345** [comment]
Maybe both solutions can be combined to create an even better one: we add a parameter to the intent that doesn't indicate a default slot but rather uniquely (perhaps together with the sending activity's name) identifies the purpose of the request (e. g. database name in case of KeePass) and remember the last used slot for each value. This way, we'd also cover users that use both slots with different configurations for different purposes. What do you think?

**Comment by aol-nnov** [comment]
To be frank, I'm a bit new to yubikey and things around it.
Let's summon someone with real usage? May be @PhilippC of keepass2android? He has recently [integrated](https://github.com/PhilippC/keepass2android/issues/4) ykDroid with his app.

**Comment by PhilippC** [comment]
I wouldn't send anything out of the database to an external app (including the database name), but I still like the id of the "purpose identifier". I can create something like a UUID for each database which I can send. Not sure if this is of high relevance. At least remembering the slot is important, though.

**Comment by pp3345** [comment]
I understand and agree with your concerns about not passing around the database name. Any unique identifier would be fine of course. I think I'll implement it this way, but please give me some time for that. I'll probably also merge this branch then.

**Comment by pp3345** [comment]
Merged this branch, thank you for your contribution. Working on the implementation for remembering slots and passing a purpose, will have something ready soon.

**Pull request merged**
